apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-two
  namespace: netdev
  labels:
    app: nginx-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-two
  template:
    metadata:
      labels:
        app: nginx-two
    spec:
      containers:
      - name: nginx-two
        image: nginxdemos/hello
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m